### PR TITLE
Developer are lazy. We need a generator for them.

### PR DESCRIPTION
**Pull request by nicolas-besnard**

### CODE REVIEW

**Comment by brandonhilkert** [comment]
:+1:

**Comment by nicolas-besnard** [comment]
When are you planning to update to gem to add this ? Not a hurry, just for information :)

**Comment by brandonhilkert** [comment]
I'll get it out sometime this weekend.

On Friday, March 6, 2015, Nicolas Besnard <notifications@github.com> wrote:

> When are you planning to update to gem to add this ? Not a hurry, just for
> information :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brandonhilkert/sucker_punch/pull/102#issuecomment-77646822>
> .
>


-- 

------------------------------------
*Build a Ruby Gem is available!
<http://brandonhilkert.com/books/build-a-ruby-gem/?utm_source=gmail-sig&utm_medium=email&utm_campaign=gmail>*

http://brandonhilkert.com

**Comment by brandonhilkert** [comment]
done `1.4.0`

**Pull request merged**
