### PR TITLE
Upgrade celluloid to 0.17.1.1 because 0.16.1 has been yanked

### PR DESCRIPTION
**Pull request by rebyn**

### CODE REVIEW

**Comment by brandonhilkert** [comment]
I think there's more to it than this. Wasn't the pools moved out to a separate gem?

**Comment by rebyn** [comment]
To be honest I wasn't really sure what I was upgrading `celluloid` for. Was just trying my luck out with the latest version; my CI has been red lately because 0.16.1 has been yanked.

**Comment by rebyn** [comment]
My bad. Ruby 2.2.3 does a few weird things on my machine. Closing this PR down, sorry for the attention @brandonhilkert :).

**Comment by brandonhilkert** [comment]
@rebyn Just released `1.5.1` that requires `0.16.0` of Celluloid. Give that a shot.

**Comment by rebyn** [comment]
@brandonhilkert works like a charm. Thanks!

**Pull request closed without merging**
